In [3]:
import numpy as np

In [4]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype="int")
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# ndarray.item(*args)
# Copy an element of an array to a standard Python scalar and return
arr.item(5)

6

In [6]:
# ndarray.tolist()
# Return the array as an a.ndim-levels deep nested list of Python scalars.
arr.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
# ndarray.itemset(*args)
# Insert scalar into an array (scalar is cast to array’s dtype, if possible
np.random.seed(123)
x = np.random.randint(9, size=(3, 3))
x
# array([[2, 2, 6],
#        [1, 3, 6],
#        [1, 0, 1]])
x.itemset(4, 0)
x.itemset((2, 2), 9)
x

array([[2, 2, 6],
       [1, 0, 6],
       [1, 0, 9]])

In [8]:
# ndarray.tobytes(order='C')
# Construct Python bytes containing the raw data bytes in the array.

x = np.array([[0, 1], [2, 3]], dtype='<u2')
x.tobytes()
# b'\x00\x00\x01\x00\x02\x00\x03\x00'
x.tobytes('C') == x.tobytes()
# True
x.tobytes('F')
# b'\x00\x00\x02\x00\x01\x00\x03\x00'

b'\x00\x00\x02\x00\x01\x00\x03\x00'

In [9]:
# ndarray.tofile(fid, sep='', format='%s')
# Write array to a file as text or binary (default).
arr.tofile("text", sep='', format='%s')

In [10]:
# ndarray.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
# Copy of the array, cast to a specified type.
arr.astype(complex)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [11]:
# ndarray.fill(value)
# Fill the array with a scalar value.
arr.fill(4)
arr

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])