In [1]:
import numpy as np

In [2]:
# numpy.take(a, indices, axis=None, out=None, mode='raise')[source]
# Take elements from an array along an axis.

a = [4, 3, 5, 7, 6, 8]
indices = [0, 1, 4]
np.take(a, indices)
# array([4, 3, 6])

# In this example if a is an ndarray, “fancy” indexing can be used.

a = np.array(a)
a[indices]
# array([4, 3, 6])

# If indices is not one dimensional, the output also has these dimensions.

np.take(a, [[0, 1], [2, 3]])
# array([[4, 3],
#        [5, 7]])

array([[4, 3],
       [5, 7]])

In [6]:
# numpy.put(a, ind, v, mode='raise')
# Replaces specified elements of an array with given values.
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
a
# array([-44,   1, -55,   3,   4])
a = np.arange(5)
np.put(a, 22, -5, mode="clip")
a
# array([ 0,  1,  2,  3, -5])

array([ 0,  1,  2,  3, -5])

In [10]:
# numpy.repeat(a, repeats, axis=None)[source]
# Repeat elements of an array

np.repeat(3, 4)
# array([3, 3, 3, 3])
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)
# array([1, 1, 2, 2, 3, 3, 4, 4])
np.repeat(x, 3, axis=1)
# array([[1, 1, 1, 2, 2, 2],
#        [3, 3, 3, 4, 4, 4]])
np.repeat(x, [1, 3], axis=1)
# array([[1, 2],
#        [3, 4],
#        [3, 4]])


array([[1, 2, 2, 2],
       [3, 4, 4, 4]])

In [11]:
# numpy.choose(a, choices, out=None, mode='raise')[source]
# Construct an array from an index array and a list of arrays to choose from.

choices = [[0, 1, 2, 3], [10, 11, 12, 13],
  [20, 21, 22, 23], [30, 31, 32, 33]]
np.choose([2, 3, 1, 0], choices
# the first element of the result will be the first element of the
# third (2+1) "array" in choices, namely, 20; the second element
# will be the second element of the fourth (3+1) choice array, i.e.,
# 31, etc.
)
# array([20, 31, 12,  3])
np.choose([2, 4, 1, 0], choices, mode='clip') # 4 goes to 3 (4-1)
# array([20, 31, 12,  3])
# because there are 4 choice arrays
np.choose([2, 4, 1, 0], choices, mode='wrap') # 4 goes to (4 mod 4)
# array([20,  1, 12,  3])
# i.e., 0



array([20,  1, 12,  3])

In [14]:
# numpy.nonzero(a)
# Return the indices of the elements that are non-zero.
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
x
# array([[3, 0, 0],
#        [0, 4, 0],
#        [5, 6, 0]])

np.nonzero(x)
# (array([0, 1, 2, 2]), array([0, 1, 0, 1]))

x[np.nonzero(x)]
# array([3, 4, 5, 6])
np.transpose(np.nonzero(x))
# array([[0, 0],
#        [1, 1],
#        [2, 0],
#        [2, 1]])

a = np.array([[1, 2], [3, 4], [5, 6]])
a
# array([[1, 2],
#        [3, 4],
#        [5, 6]])
np.compress([0, 1], a, axis=0)
# array([[3, 4]])
np.compress([False, True, True], a, axis=0)
# array([[3, 4],
#        [5, 6]])
np.compress([False, True], a, axis=1)
# array([[2],
#        [4],
#        [6]])

array([[2],
       [4],
       [6]])