In [2]:
import numpy as np

In [3]:
# numpy.take(a, indices, axis=None, out=None, mode='raise')[source]
# Take elements from an array along an axis.

a = [4, 3, 5, 7, 6, 8]
indices = [0, 1, 4]
np.take(a, indices)
# array([4, 3, 6])

# In this example if a is an ndarray, “fancy” indexing can be used.

a = np.array(a)
a[indices]
# array([4, 3, 6])

# If indices is not one dimensional, the output also has these dimensions.

np.take(a, [[0, 1], [2, 3]])
# array([[4, 3],
#        [5, 7]])

array([[4, 3],
       [5, 7]])

In [13]:
# numpy.put(a, ind, v, mode='raise')
# Replaces specified elements of an array with given values.
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
a
# array([-44,   1, -55,   3,   4])
a = np.arange(5)
np.put(a, -100, -5, mode="chip")
a
# array([ 0,  1,  2,  3, -5])

array([-5,  1,  2,  3,  4])

In [16]:
# numpy.repeat(a, repeats, axis=None)[source]
# Repeat elements of an array

np.repeat(3, 4)
# array([3, 3, 3, 3])
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)
# array([1, 1, 2, 2, 3, 3, 4, 4])
np.repeat(x, 3, axis=1)
# array([[1, 1, 1, 2, 2, 2],
#        [3, 3, 3, 4, 4, 4]])
np.repeat(x, [1, 2], axis=0)
# array([[1, 2],
#        [3, 4],
#        [3, 4]])


array([[1, 2],
       [3, 4],
       [3, 4]])

In [6]:
# numpy.choose(a, choices, out=None, mode='raise')[source]
# Construct an array from an index array and a list of arrays to choose from.

choices = [[0, 1, 2, 3], [10, 11, 12, 13],
  [20, 21, 22, 23], [30, 31, 32, 33]]
np.choose([2, 3, 1, 0], choices
# the first element of the result will be the first element of the
# third (2+1) "array" in choices, namely, 20; the second element
# will be the second element of the fourth (3+1) choice array, i.e.,
# 31, etc.
)
# array([20, 31, 12,  3])
np.choose([2, 4, 1, 0], choices, mode='clip') # 4 goes to 3 (4-1)
# array([20, 31, 12,  3])
# because there are 4 choice arrays
np.choose([2, 4, 1, 0], choices, mode='wrap') # 4 goes to (4 mod 4)
# array([20,  1, 12,  3])
# i.e., 0

array([20,  1, 12,  3])

In [7]:
# numpy.nonzero(a)
# Return the indices of the elements that are non-zero.
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
x
# array([[3, 0, 0],
#        [0, 4, 0],
#        [5, 6, 0]])

np.nonzero(x)
# (array([0, 1, 2, 2]), array([0, 1, 0, 1]))

x[np.nonzero(x)]
# array([3, 4, 5, 6])
np.transpose(np.nonzero(x))
# array([[0, 0],
#        [1, 1],
#        [2, 0],
#        [2, 1]])

a = np.array([[1, 2], [3, 4], [5, 6]])
a
# array([[1, 2],
#        [3, 4],
#        [5, 6]])
np.compress([0, 1], a, axis=0)
# array([[3, 4]])
np.compress([False, True, True], a, axis=0)
# array([[3, 4],
#        [5, 6]])
np.compress([False, True], a, axis=1)
# array([[2],
#        [4],
#        [6]])

array([[2],
       [4],
       [6]])

In [8]:
# ndarray.partition(kth, axis=- 1, kind='introselect', order=None)
# Rearranges the elements in the array in such a way that the value of the element in kth position is in the position it would be in a sorted array. All elements smaller than the kth element are moved before this element and all equal or greater are moved behind it. The ordering of the elements in the two partitions is undefined.
np.random.seed(200)
a = np.random.randint(0,100, (24,))
a
# array([26, 16, 68, 42, 55, 76, 79, 89, 14, 91, 57, 89, 11,  6, 42, 56,  1,
#         7, 51, 27, 73, 15,  1, 23])
np.partition(a, 3)
# array([ 1,  1,  6,  7, 11, 14, 23, 15, 16, 26, 57, 91, 89, 79, 42, 56, 76,
#        55, 51, 27, 73, 42, 68, 89])
a.argpartition(3)

array([22, 16, 13, 17, 12,  8, 23, 21,  1,  0, 10,  9,  7,  6, 14, 15,  5,
        4, 18, 19, 20,  3,  2, 11], dtype=int64)

In [9]:
# numpy.searchsorted(a, v, side='left', sorter=None)[source]
# Find indices where elements should be inserted to maintain order.

# Find the indices into a sorted array a such that, if the corresponding elements in v were inserted before the indices, the order of a would be preserved.
np.random.seed(200)
a = np.random.randint(0,130, (9,))
a
# array([ 26, 105,  16,  68,  42,  76,  79,  89,  14])
np.searchsorted(a, [14, 42 , 1000])

array([0, 3, 9], dtype=int64)