In [1]:
import numpy as np

In [2]:
# ndarray.reshape(shape, order='C')
# Returns an array containing the same data with a new shape.
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
# ndarray.transpose(*axes)
# Returns a view of the array with axes transposed.
a = np.array([[1, 2], [3, 4]])
# array([[1, 2],
#        [3, 4]])
a.transpose()
# array([[1, 3],
#        [2, 4]])
a.transpose((0,1))

array([[1, 2],
       [3, 4]])

In [16]:
# ndarray.swapaxes(axis1, axis2)
# Return a view of the array with axis1 and axis2 interchanged.

x = np.array([[1,2,3]])
np.swapaxes(x,1,0)
# array([[1],
#        [2],
#        [3]])

array([[1],
       [2],
       [3]])

In [17]:
# ndarray.flatten(order='C')
# Return a copy of the array collapsed into one dimension.

a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [19]:
# numpy.ravel(a, order='C')[source]
# Return a contiguous flattened array.
a = np.array([[1,2], [3,4]])

np.ravel(a, order='C')

array([1, 2, 3, 4])

In [24]:
# numpy.squeeze(a, axis=None)[source]
# Remove axes of length one from a.
x = np.array([[[0], [1], [2]]])
x.shape
# (1, 3, 1)
np.squeeze(x, axis=2).shape
# (3,)

(1, 3)