## Generating index arrays

In [2]:
import numpy as np

In [3]:
# numpy.c_ = <numpy.lib.index_tricks.CClass object>
# Translates slice objects to concatenation along the second axis.
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
# numpy.r_ = <numpy.lib.index_tricks.RClass object>
# Translates slice objects to concatenation along the first axis.

np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [5]:
# numpy.s_
# numpy.s_ = <numpy.lib.index_tricks.IndexExpression object>
# A nicer way to build up index tuples for arrays.

np.array([0, 1, 2, 3, 4])[np.s_[2::2]]

array([2, 4])

In [6]:
# numpy.where(condition, [x, y, ]/)
# Return elements chosen from x or y depending on condition.

a = np.arange(10)
a
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(a < 5, a, 2*a)

array([ 0,  1,  2,  3,  4, 10, 12, 14, 16, 18])