In [17]:
import numpy as np

In [18]:
a = np.arange(10)
a
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.clip(a, a_max=8, a_min=1)
# array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])
np.clip(a, 8, 1)
# array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
np.clip(a, [3, 4, 1, 1, 1, 4, 4, 4, 4, 4], 8)
# array([3, 4, 2, 3, 4, 5, 6, 7, 8, 8])

array([3, 4, 2, 3, 4, 5, 6, 7, 8, 8])

In [19]:
# numpy.conjugate(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'conjugate'>
# Return the complex conjugate, element-wise.


# The complex conjugate of a complex number is obtained by changing the sign of its imaginary part.

x = np.eye(2) + 1j * np.eye(2)
np.conjugate(x)
# array([[ 1.-1.j,  0.-0.j],
#        [ 0.-0.j,  1.-1.j]])


array([[1.-1.j, 0.-0.j],
       [0.-0.j, 1.-1.j]])

In [20]:
# numpy.around(a, decimals=0, out=None)
# Evenly round to the given number of decimals.
a = np.random.rand(5,5)
np.around(a, 3)

array([[0.055, 0.761, 0.14 , 0.418, 0.425],
       [0.888, 0.588, 0.052, 0.237, 0.071],
       [0.092, 0.04 , 0.068, 0.698, 0.205],
       [0.555, 0.074, 0.128, 0.356, 0.537],
       [0.094, 0.089, 0.189, 0.252, 0.936]])

In [21]:
# numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
# Return the sum along diagonals of the array.

a = np.linspace(1,24, 24, dtype=int).reshape(2,3,4)
np.trace(a),a

(array([18, 20, 22, 24]),
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]))

In [22]:
# numpy.cumsum(a, axis=None, dtype=None, out=None)
# Return the cumulative sum of the elements along a given axis.

a = np.array([[1,2,3], [4,5,6]])
a
# array([[1, 2, 3],
#        [4, 5, 6]])
a.cumsum()
# array([ 1,  3,  6, 10, 15, 21])
a.cumsum(0)

array([[1, 2, 3],
       [5, 7, 9]])

In [23]:
# numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
# Compute the arithmetic mean along the specified axis.

a = np.array([[1, 2], [3, 4]])
np.mean(a)
# 2.5
np.mean(a, axis=0)
# array([2., 3.])
np.mean(a, axis=1)
# array([1.5, 3.5])

array([1.5, 3.5])

In [24]:
# numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
# Compute the variance along the specified axis.

a = np.array([[1, 2], [3, 4]])
np.var(a)
# 1.25

1.25

In [25]:
# numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)
# Compute the standard deviation along the specified axis.

a = np.array([[1, 2], [3, 4]])
np.std(a)
# 1.1180339887498949
np.std(a, axis=0)
# array([1.,  1.])

array([1., 1.])

In [26]:
# umpy.prod(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)[source]
# Return the product of array elements over a given axis.

x = np.array([536870910, 536870910, 536870910, 536870910])
np.prod(x)
# 16 
a = np.arange(1,25).reshape(2,3,4)
np.prod(a, axis=1)

array([[  45,  120,  231,  384],
       [4641, 5544, 6555, 7680]])

In [27]:
# ndarray.cumprod(axis=None, dtype=None, out=None)
# Return the cumulative product of the elements along the given axis.

a  = np.arange(1,13).reshape(3,4)
a
# array([[ 1,  2,  3,  4],
#        [ 5,  6,  7,  8],
#        [ 9, 10, 11, 12]])
a.cumprod(axis=0)


array([[  1,   2,   3,   4],
       [  5,  12,  21,  32],
       [ 45, 120, 231, 384]])

In [28]:
# numpy.all(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)[source]
# Test whether all array elements along a given axis evaluate to True.

np.all([[True,False],[True,True]])
# False

np.all([[True,False],[True,True]], axis=0)
# array([ True, False])

np.all([[True, True], [False, True]], where=[[True], [False]])
# True

True

In [29]:
# numpy.any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)[source]
# Test whether any array element along a given axis evaluates to True.

np.any([[True, False], [True, True]])
# True
np.any([[True, False], [False, False]], axis=0)
# array([ True, False])
np.any([-1, 0, 5])
# True
np.any(np.nan)
# True
np.any([[True, False], [False, False]], where=[[False], [True]])
# False

False

In [40]:
a= np.arange(1,10).reshape(3,3)
a, np.compress((a > 2)[0,:], a , axis=1)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[3],
        [6],
        [9]]))