In [1]:
import numpy as np


In [2]:
#  Read file 
with open("data.csv", "r") as f:
    print(f.read())


anchor_ratio,trans_range,node_density,iterations,ale,sd_ale
30,15,200,40,0.773545928,0.250555301
15,15,100,70,0.911940683,0.498329391
30,15,100,50,0.814867311,0.255545506
15,20,100,20,1.435332143,0.39460254
30,15,100,40,1.265909048,0.302943301
22,18,100,24,1.457227702,0.463308546
18,23,100,14,1.912673609,0.440208313
10,25,200,15,1.432541304,0.234996306
29,25,100,40,0.777448602,0.351503738
20,20,100,30,1.142195399,0.230192531
15,20,200,20,0.694361186,0.108054554
18,23,100,16,1.536521724,0.247704526
18,23,100,24,1.054096551,0.312639571
30,15,200,70,0.616868756,0.156022817
30,20,100,50,1.306089929,0.3172243
22,18,100,18,2.568407259,0.663502187
14,17,200,40,0.857073355,0.264071316
15,15,100,60,1.360770699,0.606128956
14,17,200,70,0.761082794,0.098958496
15,20,100,40,1.400044509,0.381825484
15,15,100,40,0.968578876,0.521958738
15,20,100,70,1.236995855,0.373965312
20,20,100,20,1.424042411,0.432745628
30,15,200,50,0.623686944,0.198896422
20,20,200,30,0.639524158,0.144813998
27,12,300,34,0.527

In [3]:
# Create a array
arr = [[1,2,3,4], [5,6,7,8], [10,11,12,13]]

new_arr = np.array(arr, dtype=int)
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [4]:
# Use function arange
# Set rows and columns by reshape
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
# Get shape of arr
shape = a.shape
shape


(3, 5)

In [6]:
# get length of arr
size = a.size 
size

15

In [7]:
# Create zeros array
zero_arr = np.zeros((3,4),dtype=int)
zero_arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
# Create array one
one_arr = np.ones((3,4),dtype=int)
one_arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
# Empty arr
np.empty((2,5), dtype=int)

array([[         0,          1,          0,        488,       1108],
       [         0,        768,      32761, 1889427952,        488]])

In [10]:
# Create array of lineshape
np.linspace(1,5, 10).reshape(5,2)

array([[1.        , 1.44444444],
       [1.88888889, 2.33333333],
       [2.77777778, 3.22222222],
       [3.66666667, 4.11111111],
       [4.55555556, 5.        ]])

In [11]:
# Random
rg = np.random.default_rng(2)
arr = rg.random((2,3))
new_arr = np.random.randint(23, size=(6,6))

new_arr

array([[18,  6, 22,  2, 16, 22],
       [11, 17,  9, 12, 15, 15],
       [ 0,  9, 16,  9, 13, 22],
       [ 7, 14,  0, 17,  8, 16],
       [20, 21, 21,  4,  1, 12],
       [14, 10, 20,  0,  0,  0]])

In [12]:
# get element
arr = np.arange(100).reshape(10,10)
arr[1,1]

11

In [13]:
# Ravel Arr
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
arr.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [15]:
# Columns stack
a = [1,2,3,4]
b = [4,5,6,7]
# np.vstack((a,b))
# a[:, np.newaxis]
np.row_stack((a, b))

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [16]:
from numpy import newaxis

a = [1,2,3,4,5,6,7,8,9,10]
a = np.array(a)
a[:, newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [17]:
# H_split
b = np.hsplit(a, 10)

In [18]:
a = [1, 2, 3]
b =[4, 5, 6]
new_a = np.concatenate((a, b))
new_a

array([1, 2, 3, 4, 5, 6])

In [19]:
# np.view and np.copy
a = [1, 2, 3, 4, 5, 6, 7, 8, 9	]
a = np.array(a)
b = a.view()
b


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# np.unique
arr = [1, 1, 1, 1, 2, 3 ,3 ,4, 4, 3, 2]
arr, data = np.unique(arr, return_inverse=True)
data

array([0, 0, 0, 0, 1, 2, 2, 3, 3, 2, 1], dtype=int64)

In [21]:
# np.flatten and np.ravel
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a = x.ravel()
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
# Save file and load file
a = np.array([1, 2, 3, 4, 5, 6])
np.save('filename', a)
b = np.load('filename.npy')

In [23]:
# np.diag
a = [1,2,3]
b = [4,5,6]
c = np.diag((a, b))
c

array([1, 5])

In [24]:
A=np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])


array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [25]:
from io import StringIO
data = u"  1  2  3\n  4  5 67\n890123  4"
np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [26]:
big_end_buffer = bytearray([0,1,3,2])
big_end_buffer

bytearray(b'\x00\x01\x03\x02')

In [ ]:
# Structured arrays
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
x['name']