In [6]:
import torch

In [33]:
img_t = torch.randint(1, 10, (3, 5, 5)) # shape [channels, rows, columns]
weights = torch.tensor([2, 4, 6])

In [34]:
batch_t = torch.randint(1, 10, (2, 3, 5, 5)) # shape [batch, channels, rows, columns]

In [55]:
img_gray_naive = img_t.type(torch.float32).mean(-3)
batch_gray_naive = batch_t.type(torch.float32).mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [56]:
img_t

tensor([[[8, 4, 8, 2, 9],
         [4, 9, 7, 3, 2],
         [3, 8, 1, 7, 4],
         [9, 8, 8, 3, 6],
         [1, 7, 7, 5, 5]],

        [[6, 8, 5, 3, 1],
         [1, 5, 1, 9, 1],
         [5, 3, 4, 3, 2],
         [2, 2, 1, 5, 3],
         [2, 9, 2, 5, 4]],

        [[7, 9, 3, 9, 6],
         [6, 3, 1, 4, 3],
         [4, 8, 2, 4, 5],
         [9, 5, 9, 7, 6],
         [4, 5, 7, 1, 2]]])

In [57]:
img_gray_naive

tensor([[7.0000, 7.0000, 5.3333, 4.6667, 5.3333],
        [3.6667, 5.6667, 3.0000, 5.3333, 2.0000],
        [4.0000, 6.3333, 2.3333, 4.6667, 3.6667],
        [6.6667, 5.0000, 6.0000, 5.0000, 5.0000],
        [2.3333, 7.0000, 5.3333, 3.6667, 3.6667]])

In [58]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [62]:
print(unsqueezed_weights)
print(img_t)

tensor([[[2]],

        [[4]],

        [[6]]])
tensor([[[8, 4, 8, 2, 9],
         [4, 9, 7, 3, 2],
         [3, 8, 1, 7, 4],
         [9, 8, 8, 3, 6],
         [1, 7, 7, 5, 5]],

        [[6, 8, 5, 3, 1],
         [1, 5, 1, 9, 1],
         [5, 3, 4, 3, 2],
         [2, 2, 1, 5, 3],
         [2, 9, 2, 5, 4]],

        [[7, 9, 3, 9, 6],
         [6, 3, 1, 4, 3],
         [4, 8, 2, 4, 5],
         [9, 5, 9, 7, 6],
         [4, 5, 7, 1, 2]]])


In [67]:
img_weights

tensor([[[16,  8, 16,  4, 18],
         [ 8, 18, 14,  6,  4],
         [ 6, 16,  2, 14,  8],
         [18, 16, 16,  6, 12],
         [ 2, 14, 14, 10, 10]],

        [[24, 32, 20, 12,  4],
         [ 4, 20,  4, 36,  4],
         [20, 12, 16, 12,  8],
         [ 8,  8,  4, 20, 12],
         [ 8, 36,  8, 20, 16]],

        [[42, 54, 18, 54, 36],
         [36, 18,  6, 24, 18],
         [24, 48, 12, 24, 30],
         [54, 30, 54, 42, 36],
         [24, 30, 42,  6, 12]]])

In [68]:
batch_weights = (batch_t * unsqueezed_weights)

In [71]:
import torch

A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([2, 3])

result = torch.einsum('ij,j->i', A, B)
result

tensor([ 8, 18])

In [79]:
X = torch.tensor([1, 2, 3])
Y = torch.tensor([4, 5, 6])

torch.einsum('i,j ->j', X, Y)

tensor([24, 30, 36])

In [80]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

C:\Users\DELL\AppData\Local\Temp\ipykernel_10636\2338252810.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10/core/TensorImpl.h:1791.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [84]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')
