In [1]:
import torch

In [77]:

a = torch.randint(1, 10, (2, 3))
b = torch.randint(1, 10, (2,3))
c = torch.randint(1, 10, (2,3))

a, b

(tensor([[8, 2, 1],
         [5, 9, 5]]),
 tensor([[8, 4, 3],
         [7, 6, 4]]))

In [83]:
torch.einsum('ik , jk -> i' , a , b)

tensor([147, 200])