In [3]:
import tensorflow as tf

### Creating Tensors

In [6]:
string = tf.Variable('this is a string', tf.string)
number = tf.Variable(231, tf.int16)
floating = tf.Variable(3.43, tf.float16)
print(string, number, floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'> <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=231> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.43>


### Rank and degrees

In [8]:
matrix_1 = tf.Variable(['test'], tf.string)
matrix_2 = tf.Variable([[1,2], [3,4]], tf.int16)
tf.rank(matrix_2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [9]:
#shape
matrix_2.shape

TensorShape([2, 2])

### Reshape

In [19]:
tensor_1 = tf.ones([1,2,3])
tensor_2 = tf.reshape(tensor_1, shape=[2,3,1])
tensor_3 = tf.reshape(tensor_2, shape=[3,-1])

In [20]:
print(tensor_1)
print(tensor_2)
print(tensor_3)


tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
