In [4]:
import numpy as np


In [5]:
#  Read file 
with open("data.csv", "r") as f:
    print(f.read())


FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
# Create a array
arr = [[1,2,3,4], [5,6,7,8], [10,11,12,13]]

new_arr = np.array(arr, dtype=int)
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [ ]:
# Use function arange
# Set rows and columns by reshape
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# Get shape of arr
shape = a.shape
shape


(3, 5)

In [ ]:
# get length of arr
size = a.size 
size

15

In [ ]:
# Create zeros array
zero_arr = np.zeros((3,4),dtype=int)
zero_arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# Create array one
one_arr = np.ones((3,4),dtype=int)
one_arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# Empty arr
np.empty((2,5), dtype=int)

array([[         0,          1,          0,        488,       1108],
       [         0,        768,      32761, 1889427952,        488]])

In [ ]:
# Create array of lineshape
np.linspace(1,5, 10).reshape(5,2)

array([[1.        , 1.44444444],
       [1.88888889, 2.33333333],
       [2.77777778, 3.22222222],
       [3.66666667, 4.11111111],
       [4.55555556, 5.        ]])

In [ ]:
# Random
rg = np.random.default_rng(2)
arr = rg.random((2,3))
new_arr = np.random.randint(23, size=(6,6))

new_arr

array([[18,  6, 22,  2, 16, 22],
       [11, 17,  9, 12, 15, 15],
       [ 0,  9, 16,  9, 13, 22],
       [ 7, 14,  0, 17,  8, 16],
       [20, 21, 21,  4,  1, 12],
       [14, 10, 20,  0,  0,  0]])

In [ ]:
# get element
arr = np.arange(100).reshape(10,10)
arr[1,1]

11

In [ ]:
# Ravel Arr
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [10]:
# Columns stack
a = [1,2,3,4]
b = [4,5,6,7]
# np.vstack((a,b))
# a[:, np.newaxis]
np.row_stack((a, b))
np.hstack((a,b))
np.concatenate((a,b) )

array([1, 2, 3, 4, 4, 5, 6, 7])

In [17]:
from numpy import newaxis

a = [1,2,3,4,5,6,7,8,9,10]
a = np.array(a)
a[:, newaxis]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# H_split and v_split
np.vsplit(np.array([[1],[2],[3],[4]]), 4)
np.hsplit(np.array([1,2,3,4]), 4)

[array([[1]]), array([[2]]), array([[3]]), array([[4]])]

In [ ]:
a = [1, 2, 3]
b =[4, 5, 6]
new_a = np.concatenate((a, b))
new_a

array([1, 2, 3, 4, 5, 6])

In [ ]:
# np.view and np.copy
a = [1, 2, 3, 4, 5, 6, 7, 8, 9	]
a = np.array(a)
b = a.view()
b


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# np.unique
arr = [1, 1, 1, 1, 2, 3 ,3 ,4, 4, 3, 2]
arr, data = np.unique(arr, return_inverse=True)
data

array([0, 0, 0, 0, 1, 2, 2, 3, 3, 2, 1], dtype=int64)

In [ ]:
# np.flatten and np.ravel
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a = x.ravel()
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Save file and load file
a = np.array([1, 2, 3, 4, 5, 6])
np.save('filename', a)
b = np.load('filename.npy')

In [20]:
# np.diag
a = [1,2,3]
b = [4,5,6]
c = np.diag((a, b))
c

array([1, 5])

In [28]:
A=np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])
# A,B,C,D



array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

In [ ]:
from io import StringIO
data = u"  1  2  3\n  4  5 67\n890123  4"
np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [ ]:
big_end_buffer = bytearray([0,1,3,2])
big_end_buffer

bytearray(b'\x00\x01\x03\x02')

In [ ]:
# Structured arrays
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
x['name']